import React, {useEffect,useState} from 'react';
import {KeyRound, Plus, RefreshCw, Trash2, Wifi} from 'lucide-react';
import {changeInternetPassword,createEmployeeInternetAccount,createInternetAccount,deleteInternetAccount,fetchInternetAccounts,InternetAccount,updateInternetAccount} from '../api';
import {Resident} from '../types';

export default function InternetAccessModule({showToast}:{showToast:(message:string,type?:'success'|'warning'|'error')=>void}){
 const [rows,setRows]=useState<InternetAccount[]>([]); const [residents,setResidents]=useState<Resident[]>([]); const [apartment,setApartment]=useState(''); const [busy,setBusy]=useState(false); const [password,setPassword]=useState<string|null>(null);
 const [employeeName,setEmployeeName]=useState('');const [employeeUsername,setEmployeeUsername]=useState('');const [employeePassword,setEmployeePassword]=useState('');const [enrollmentPassword,setEnrollmentPassword]=useState('');
 const load=async()=>{try{const [accounts,residentResponse]=await Promise.all([fetchInternetAccounts(),fetch('/api/residents')]);if(!residentResponse.ok)throw new Error('Não foi possível carregar os moradores');setRows(accounts);setResidents((await residentResponse.json()) as Resident[])}catch(e){showToast(e instanceof Error?e.message:'Falha ao carregar acessos','error')}};
 useEffect(()=>{void load()},[]);
 const create=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{await createInternetAccount(apartment);setPassword(null);setApartment('');await load();showToast('Internet ativada por 90 dias. A senha foi enviada por e-mail.')}catch(e){showToast(e instanceof Error?e.message:'Falha ao ativar acesso','error')}finally{setBusy(false)}};
 const reset=async(row:InternetAccount)=>{if(!confirm('Trocar a senha e desconectar todos os aparelhos desta conta?'))return;try{const r=await changeInternetPassword(row.id);if(row.account_type==='employee')setPassword(r.generated_password||null);else setPassword(null);await load();showToast(row.account_type==='employee'?'Senha trocada e sessões revogadas.':'Senha trocada, sessões revogadas e enviada por e-mail.')}catch(e){showToast(e instanceof Error?e.message:'Não foi possível trocar a senha','error')}};
 const remove=async(id:string)=>{if(!confirm('Remover o acesso e desconectar todos os aparelhos?'))return;try{await deleteInternetAccount(id);await load();showToast('Acesso removido.')}catch(e){showToast(e instanceof Error?e.message:'Falha ao remover acesso','error')}};
 const toggle=async(row:InternetAccount)=>{try{await updateInternetAccount({...row,enabled:!row.enabled});await load()}catch(e){showToast(e instanceof Error?e.message:'Falha ao alterar acesso','error')}};
 const createEmployee=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{await createEmployeeInternetAccount(employeeName,employeeUsername,employeePassword,enrollmentPassword);setEmployeeName('');setEmployeeUsername('');setEmployeePassword('');setEnrollmentPassword('');await load();showToast('Funcionário cadastrado com acesso por 30 dias.')}catch(e){showToast(e instanceof Error?e.message:'Falha ao cadastrar funcionário','error')}finally{setBusy(false)}};
 const residentRows=rows.filter(r=>r.account_type!=='employee');const employeeRows=rows.filter(r=>r.account_type==='employee');
 return <div className="space-y-5 font-mono">
  <div className="bg-[#0a0d14] border border-slate-800/40 p-5 rounded-sm"><div className="flex items-center gap-2 mb-4"><Wifi size={16} className="text-emerald-400"/><h2 className="text-sm uppercase font-bold tracking-widest">Internet dos apartamentos</h2></div><p className="text-[10px] text-slate-500 mb-3 uppercase">Acesso por 90 dias. Somente apartamentos já cadastrados em Moradores e com e-mail válido podem receber acesso. A senha será enviada ao inquilino ou, na ausência dele, ao morador.</p><form onSubmit={create} className="grid sm:grid-cols-[1fr_auto] gap-3"><select value={apartment} onChange={e=>setApartment(e.target.value)} required className="bg-slate-950 border border-slate-800 p-2 text-xs"><option value="">Selecione um apartamento cadastrado</option>{residents.filter(r=>(r.owner||r.tenant)&&!rows.some(a=>a.apartment===r.unit)).map(r=><option key={r.unit} value={r.unit}>Apartamento {r.unit} — {r.tenant||r.owner}</option>)}</select><button disabled={busy||!apartment} className="bg-emerald-950 border border-emerald-500/30 text-emerald-400 px-4 text-xs uppercase font-bold flex items-center justify-center gap-2"><Plus size={13}/>{busy?'Ativando':'Ativar internet'}</button></form>{password&&<div className="mt-4 border border-amber-500/40 bg-amber-950/20 p-3 text-amber-300 text-xs">Senha de funcionário gerada (exibida somente agora): <strong className="text-base ml-2 select-all">{password}</strong><button onClick={()=>setPassword(null)} className="ml-4 text-slate-400">Ocultar</button></div>}</div>
  <AccountTable title="Moradores" rows={residentRows} speed="30 Mbps ↓ / 30 Mbps ↑" onToggle={toggle} onReset={reset} onRemove={remove}/>
  <div className="bg-[#0a0d14] border border-slate-800/40 p-5 rounded-sm"><h2 className="text-sm uppercase font-bold tracking-widest mb-1">Funcionários</h2><p className="text-[10px] text-slate-500 mb-3 uppercase">Acesso por 30 dias, com 10 Mbps de download e upload.</p><form onSubmit={createEmployee} className="grid md:grid-cols-2 lg:grid-cols-5 gap-3"><input value={employeeName} onChange={e=>setEmployeeName(e.target.value)} required placeholder="Nome do funcionário" className="bg-slate-950 border border-slate-800 p-2 text-xs"/><input value={employeeUsername} onChange={e=>setEmployeeUsername(e.target.value)} required placeholder="Usuário" className="bg-slate-950 border border-slate-800 p-2 text-xs"/><input type="password" value={employeePassword} onChange={e=>setEmployeePassword(e.target.value)} required placeholder="Senha de acesso (livre)" className="bg-slate-950 border border-slate-800 p-2 text-xs"/><input type="password" value={enrollmentPassword} onChange={e=>setEnrollmentPassword(e.target.value)} required placeholder="Senha para cadastrar" className="bg-slate-950 border border-slate-800 p-2 text-xs"/><button disabled={busy} className="bg-sky-950 border border-sky-500/30 text-sky-400 px-4 text-xs uppercase font-bold">Cadastrar funcionário</button></form></div>
  <AccountTable title="Acessos de funcionários" rows={employeeRows} speed="10 Mbps ↓ / 10 Mbps ↑" onToggle={toggle} onReset={reset} onRemove={remove}/>
 </div>
}

function AccountTable({title,rows,speed,onToggle,onReset,onRemove}:{title:string;rows:InternetAccount[];speed:string;onToggle:(r:InternetAccount)=>Promise<void>;onReset:(r:InternetAccount)=>Promise<void>;onRemove:(id:string)=>Promise<void>}){return <div className="bg-[#0a0d14] border border-slate-800/40 rounded-sm overflow-x-auto"><h3 className="p-3 text-xs uppercase font-bold tracking-wider">{title}</h3><table className="w-full text-xs"><thead className="text-slate-500 uppercase"><tr><th className="p-3 text-left">Nome/Unidade</th><th className="p-3 text-left">Usuário</th><th className="p-3">Validade</th><th className="p-3">Conexões</th><th className="p-3">Velocidade</th><th className="p-3">Ações</th></tr></thead><tbody>{rows.map(row=><tr key={row.id} className="border-t border-slate-900"><td className="p-3 font-bold">{row.name||row.apartment}</td><td className="p-3">{row.username}</td><td className="p-3 text-center">{new Date(row.expires_at).toLocaleDateString('pt-BR')}</td><td className="p-3 text-center">{row.active_connections}/{row.max_connections}</td><td className="p-3 text-center">{speed}</td><td className="p-3"><div className="flex justify-center gap-2"><button onClick={()=>void onToggle(row)} className={row.enabled?'text-emerald-400':'text-red-400'}>{row.enabled?'Ativo':'Bloqueado'}</button><button title="Trocar senha" onClick={()=>void onReset(row)} className="text-amber-400"><KeyRound size={14}/></button><button title="Remover" onClick={()=>void onRemove(row.id)} className="text-red-400"><Trash2 size={14}/></button></div></td></tr>)}</tbody></table>{rows.length===0&&<div className="p-6 text-center text-slate-600 text-xs">Nenhum acesso cadastrado.</div>}<button onClick={()=>location.reload()} className="m-3 text-slate-500 flex gap-1 items-center"><RefreshCw size={12}/> Atualizar</button></div>}
